// Command engc compiles rime-ice's English dictionaries into the flat table
// internal/english embeds.
//
//	go run ./apps/q-ime/tools/engc \
//	    -src /opt/test/rime-ice/en_dicts \
//	    -o apps/q-ime/internal/english/data/english.txt
//
// Why rime-ice rather than a raw frequency list: its en.dict.yaml is the top
// ~20k of google-10000-english ALREADY CURATED for use inside a pinyin input
// method, and the curation is the valuable part —
//
//   - single letters and most two-letter abbreviations are commented out,
//     which is exactly the set that would otherwise fight every pinyin
//     abbreviation ("j" is not the English word "J");
//   - words that should be capitalized are stored capitalized, so typing
//     "iphone" can produce "iPhone" and "aaron" can produce "Aaron" without
//     this tool guessing at case;
//   - the entries are keyed by what you TYPE, not by how they are spelled, so
//     "he'll" is reachable from "hell" and "Buenos Aires" from "buenosaires".
//
// It is also the same upstream, at the same version, as the Chinese lexicon —
// one licence (GPL-3.0) and one thing to update instead of two.
//
// The output is deliberately a sorted text file rather than a packed binary:
// it is ~200KB, it is read-only, it is diffable in review, and embedding it
// means the app has no second data file to go looking for at startup. The
// large lexicon is external because it is 76MB; this is not.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Sources, in the order rime-ice's own melt_eng.dict.yaml imports them:
// en_ext first, because the handful of weighted entries live there and a
// weight has to be seen before the unweighted duplicate in en.
var sources = []string{"en_ext.dict.yaml", "en.dict.yaml"}

// minCodeLen drops single-letter codes.
//
// A lone letter is how this input method spells an ABBREVIATED syllable — "j"
// means "some syllable starting with j" — so an English candidate there is
// noise on top of the one keystroke where the candidate list is least settled.
// rime-ice reached the same conclusion and comments them out; this enforces it
// for anything that slips through.
const minCodeLen = 2

// maxTextsPerCode caps how many words one code may produce.
//
// Codes are not unique: rime-ice files "iPhone", "iPhone 17" and "iPhone 17
// Pro" all under the code "iphone". Capping here rather than in the reader
// keeps the reader dumb — whatever is in the file is what gets offered.
const maxTextsPerCode = 4

type entry struct {
	text   string
	weight int
	order  int // position across all input files, for a stable tiebreak
}

func main() {
	var (
		src = flag.String("src", "/opt/test/rime-ice/en_dicts",
			"directory holding rime-ice's en.dict.yaml and en_ext.dict.yaml")
		out = flag.String("o", "apps/q-ime/internal/english/data/english.txt",
			"table to write")
	)
	flag.Parse()

	byCode := map[string][]entry{}
	order := 0
	var stats struct{ read, skipped int }

	for _, name := range sources {
		path := filepath.Join(*src, name)
		f, err := os.Open(path)
		if err != nil {
			fatal("%v", err)
		}
		body := false
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			line := strings.TrimRight(sc.Text(), "\r")
			// Rime dictionaries are a YAML header, then "...", then the
			// entries. Reading the header as entries would file "name: en" as
			// a word.
			if !body {
				if line == "..." {
					body = true
				}
				continue
			}
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}
			text, code, weight, ok := parse(line)
			stats.read++
			if !ok {
				stats.skipped++
				continue
			}
			byCode[code] = append(byCode[code], entry{text, weight, order})
			order++
		}
		if err := sc.Err(); err != nil {
			fatal("%s: %v", path, err)
		}
		f.Close()
		fmt.Fprintf(os.Stderr, "engc: read %s\n", path)
	}

	codes := make([]string, 0, len(byCode))
	for code := range byCode {
		codes = append(codes, code)
	}
	sort.Strings(codes)

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by apps/q-ime/tools/engc. Do not edit.\n")
	fmt.Fprintf(&b, "# Source: rime-ice en_dicts (GPL-3.0), itself derived from\n")
	fmt.Fprintf(&b, "# google-10000-english and rime-melt. One line per typing\n")
	fmt.Fprintf(&b, "# code: code<TAB>text...  — texts best-first, codes sorted.\n")

	texts := 0
	for _, code := range codes {
		list := dedupe(byCode[code])
		if len(list) == 0 {
			continue
		}
		b.WriteString(code)
		for _, e := range list {
			b.WriteByte('\t')
			b.WriteString(e.text)
		}
		b.WriteByte('\n')
		texts += len(list)
	}

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fatal("%v", err)
	}
	if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
		fatal("%v", err)
	}
	fmt.Fprintf(os.Stderr,
		"engc: %d codes, %d words, %d entries skipped as untypeable, %.0fKB → %s\n",
		len(codes), texts, stats.skipped, float64(b.Len())/1024, *out)
}

// parse reads one dictionary line: text, typing code, optional weight.
//
// The code is what the user presses, so it is rejected unless it is something
// this input method can actually receive: lowercase letters only. Digits are
// how a candidate is picked while composing, so a code containing one — the
// "manifestv3" of the world — can never be typed and would only bloat the
// table.
func parse(line string) (text, code string, weight int, ok bool) {
	f := strings.Split(line, "\t")
	if len(f) < 2 {
		return "", "", 0, false
	}
	text, code = f[0], strings.ToLower(f[1])
	if text == "" || len(code) < minCodeLen || !onlyLetters(code) {
		return "", "", 0, false
	}
	if len(f) >= 3 {
		if w, err := strconv.Atoi(strings.TrimSpace(f[2])); err == nil {
			weight = w
		}
	}
	return text, code, weight, true
}

func onlyLetters(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] < 'a' || s[i] > 'z' {
			return false
		}
	}
	return true
}

// dedupe orders one code's words best-first and trims to the cap.
//
// Weight descending, then file order — which is en_ext before en, matching how
// rime-ice layers them: the weighted entries are the disambiguations somebody
// bothered to make ("hell" 2 before "he'll" 1) and they have to win.
func dedupe(list []entry) []entry {
	sort.SliceStable(list, func(i, j int) bool {
		if list[i].weight != list[j].weight {
			return list[i].weight > list[j].weight
		}
		return list[i].order < list[j].order
	})
	seen := make(map[string]bool, len(list))
	out := list[:0]
	for _, e := range list {
		if seen[e.text] {
			continue
		}
		seen[e.text] = true
		out = append(out, e)
		if len(out) == maxTextsPerCode {
			break
		}
	}
	return out
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "engc: "+format+"\n", args...)
	os.Exit(1)
}
