#import <Cocoa/Cocoa.h>
#import <InputMethodKit/InputMethodKit.h>
// For kTSMHiliteSelectedRawText. The Carbon Text Services hilite styles are
// what IMK actually puts in a marked string's NSMarkedClauseSegment attribute
// — see quiMarkedText.
#import <Carbon/Carbon.h>

#import "bridge_darwin.h"
// Generated by cgo; declares the quiIMEGo* functions implemented in Go.
#include "_cgo_export.h"

static IMKServer *gServer = nil;

// gController is the controller that most recently handled an event.
//
// Needed because markForStyle:atRange: — the only correct way to build a
// marked string's attributes — is an IMKInputController INSTANCE method, while
// the functions Go calls have only the client. Weak, so a controller whose
// text field has gone away is not kept alive by this.
//
// Not a contradiction of "the controller stays stateless": no per-client state
// lives on the controller. This records WHICH controller is current, the same
// thing the Go side already tracks with its cached client, and for the same
// reason — a process-wide composition has exactly one of each at a time.
static __weak IMKInputController *gController = nil;

// --- the controller IMK instantiates ---------------------------------

// One instance PER TEXT CLIENT — IMK creates a controller for every text
// field that activates this input method. So the controller must stay
// stateless: the composition buffer and the candidate panel are
// process-wide and live in Go. Putting state here would give each text
// field its own private half of the input method.
@interface QuiIMEController : IMKInputController
@end

@implementation QuiIMEController

// Key-down and modifier transitions. Mouse events stay excluded; nothing
// here uses them.
- (NSUInteger)recognizedEvents:(id)sender {
    return NSEventMaskKeyDown | NSEventMaskFlagsChanged;
}

// This input method uses IMKServerInput's THIRD approach: raw NSEvents.
//
// IMKInputController.h describes three mutually exclusive ways to receive
// events and says "An input method should choose one of those ways":
//
//   1. inputText:client: + didCommandBySelector:client:   (with keybinding)
//   2. inputText:key:modifiers:client:                    ("without the
//                                                          keybinding")
//   3. handleEvent:client:                                (raw NSEvent)
//
// Approach 3 is the only one that sees modifier transitions, which the
// Shift-to-switch-language gesture needs, and it also carries key-downs,
// unpacked below. Approach 2 is documented as delivering key events *without
// the keybinding*, so didCommandBySelector: would never be called alongside
// it; and implementing both 2 and 3 makes IMK pick one, which is how
// flags-changed ends up never arriving. Approach 3 alone is deliberate, and
// so is not calling super (super performs the approach 1/2 dispatch, and both
// paths live would double-handle every key).
//
// Special keys are dispatched by KEY CODE on the Go side, since that is the
// only thing that identifies them.
- (BOOL)handleEvent:(NSEvent *)event client:(id)sender {
    @autoreleasepool {
        gController = self;
        switch (event.type) {
        case NSEventTypeFlagsChanged:
            return qimeBridgeGoFlags((__bridge void *)sender,
                                     (unsigned int)event.modifierFlags,
                                     (int)event.keyCode) != 0;
        case NSEventTypeKeyDown: {
            // characters is nil for some dead-key states; an empty string
            // still carries a usable key code, so don't drop the event.
            const char *chars = [[event characters] UTF8String];
            return qimeBridgeGoKey((__bridge void *)sender,
                                   (char *)(chars ? chars : ""),
                                   (int)event.keyCode,
                                   (unsigned int)event.modifierFlags) != 0;
        }
        default:
            return NO;
        }
    }
}

// The string currently being composed.
//
// IMK asks for this rather than tracking what we sent, and the default answer
// is nothing at all. Answering costs six lines and makes the framework's view
// of the composition agree with the client's; it cannot disagree with what was
// last sent through setMarkedText, because both come from the same preedit.
- (id)composedString:(id)sender {
    char *s = qimeBridgeGoComposedString();
    if (s == NULL) return @"";
    NSString *composed = [NSString stringWithUTF8String:s];
    free(s); // allocated by Go's C.CString
    return composed;
}

// Focus is leaving. Not flushing here is the classic "ghost underline"
// bug: the host app keeps a marked range nothing will ever finish.
- (void)commitComposition:(id)sender {
    qimeBridgeGoCommand((__bridge void *)sender, "commitComposition:");
}

- (void)deactivateServer:(id)sender {
    qimeBridgeGoDeactivate((__bridge void *)sender);
}

// A pick from the 候选词数量 rows. The tag IS the candidate count.
//
// NO TARGET is set on those items, deliberately. IMK does not dispatch this
// through the responder chain: the menu-bar agent hands the selector back to
// IMK, whose doCommandBySelector:commandDictionary: performs it on the
// controller. The header is explicit — "an input method merely needs to
// provide actions for each menu item" — and a target pointer cannot cross the
// process boundary.
//
// THE SENDER IS NOT THE MENU ITEM. The input-source menu is rendered by the
// system's menu-bar agent, in another process, so a pick comes back as what
// IMKInputController.h calls the infoDictionary — the item itself is a COPY
// inside it, under kIMKCommandMenuItemName. That constant exists for no other
// reason, and the header says so: "An NSMenuItem in the infoDictionary passed
// to menu item actions."
//
// An unrecognised sender shape is logged rather than returned silently,
// because a menu that quietly does nothing is indistinguishable from a menu
// that was never wired up.
//
// Worth knowing if you go looking: those headers are ISO-8859 encoded, so
// grep treats them as binary and finds nothing. Use `grep -a`.
//
// Each command IMK routes here from the input-method menu is logged, then
// handled by IMK's own implementation. Pure instrumentation: super does the
// work. It exists because "a pick that goes nowhere" and "a menu that was
// never wired up" produce exactly the same nothing, and this is the one
// documented door every menu command comes through.
- (void)doCommandBySelector:(SEL)aSelector commandDictionary:(NSDictionary *)infoDictionary {
    qimeBridgeGoLog((char *)[[NSString stringWithFormat:@"menu command: %@",
                              NSStringFromSelector(aSelector)] UTF8String]);
    [super doCommandBySelector:aSelector commandDictionary:infoDictionary];
}

- (void)qimeSetPageSize:(id)sender {
    // The Go side touches the session and the candidate panel's widget tree,
    // both of which are owned by the thread qui pinned at startup. A menu pick
    // arrives over IMK's mach port and so should already be on it; hopping when
    // it is not costs four lines and removes the need to be right about that.
    if (![NSThread isMainThread]) {
        dispatch_async(dispatch_get_main_queue(), ^{ [self qimeSetPageSize:sender]; });
        return;
    }

    NSMenuItem *item = nil;
    if ([sender isKindOfClass:[NSMenuItem class]]) {
        item = sender; // a local menu, e.g. if IMK ever stops proxying
    } else if ([sender isKindOfClass:[NSDictionary class]]) {
        // Cast away the const of Apple's `const NSString *` declaration; the
        // parameter is id, and the pointee is never touched.
        id picked = [(NSDictionary *)sender
            objectForKey:(NSString *)kIMKCommandMenuItemName];
        if ([picked isKindOfClass:[NSMenuItem class]]) item = picked;
    }
    if (item == nil) {
        qimeBridgeGoLog((char *)[[NSString
            stringWithFormat:@"menu: pick arrived as %@, no NSMenuItem in it: %@",
                             [sender class], sender] UTF8String]);
        return;
    }
    qimeBridgeGoSetPageSize((int)[item tag]);
}

// Visible under the input-source menu-bar item; proof the process is alive
// and that IMK resolved this class by name.
//
// It is also the only settings surface this input method has, which is why the
// candidate count is here rather than in a preferences window: an IME has no
// Dock icon and never activates, so a window of its own is one nothing can
// bring to the front. Everything else stays in prefs.json.
- (NSMenu *)menu {
    NSMenu *menu = [[NSMenu alloc] initWithTitle:@"qui IME"];
    // Every item here says whether it is enabled, so stop AppKit asking a
    // responder chain that does not exist in this never-activating process.
    [menu setAutoenablesItems:NO];
    NSMenuItem *banner = [[NSMenuItem alloc] initWithTitle:@"qui 拼音 — Go + qui panel"
                                                    action:NULL
                                             keyEquivalent:@""];
    [banner setEnabled:NO];
    [menu addItem:banner];
    [menu addItem:[NSMenuItem separatorItem]];

    // How many candidates the panel offers.
    //
    // FLAT rows under a disabled label, not a submenu: nothing in IMK
    // documents a nested menu surviving the trip to the menu-bar agent.
    // Indentation buys the grouping a submenu was there for, and costs
    // nothing that has to be serialized.
    //
    // The bounds come from Go rather than from the numbers written out a
    // second time here: one place decides what is allowed, and it is the
    // place that enforces it.
    int lo = 0, hi = 0;
    qimeBridgeGoPageSizeBounds(&lo, &hi);
    int current = (int)qimeBridgeGoPageSize();
    NSMenuItem *sizeLabel = [[NSMenuItem alloc] initWithTitle:@"候选词数量"
                                                       action:NULL
                                                keyEquivalent:@""];
    [sizeLabel setEnabled:NO];
    [menu addItem:sizeLabel];
    for (int n = lo; n <= hi; n++) {
        NSMenuItem *item =
            [[NSMenuItem alloc] initWithTitle:[NSString stringWithFormat:@"%d 个", n]
                                       action:@selector(qimeSetPageSize:)
                                keyEquivalent:@""];
        [item setTag:n];
        [item setIndentationLevel:1];
        [item setEnabled:YES];
        [item setState:(n == current) ? NSControlStateValueOn : NSControlStateValueOff];
        [menu addItem:item];
    }
    [menu addItem:[NSMenuItem separatorItem]];

    // A shortcut nobody can find is half a feature, and this one has no other
    // surface: it only does anything while a candidate is highlighted, which is
    // exactly when this menu cannot be open. Disabled on purpose — it is a
    // reminder, not a command, because there is nothing to act on from here.
    for (NSString *tip in @[ @"上屏中文：空格键或数字键",
                            @"上屏原始字母：输入时按 Enter",
                            @"忘记候选词：输入时按 Shift+⌫" ]) {
        NSMenuItem *item = [[NSMenuItem alloc] initWithTitle:tip
                                                     action:NULL
                                              keyEquivalent:@""];
        [item setEnabled:NO];
        [menu addItem:item];
    }
    [menu addItem:[NSMenuItem separatorItem]];

    [menu addItemWithTitle:@"退出 QuiIME"
                    action:@selector(terminate:)
             keyEquivalent:@""];
    return menu;
}

@end

// --- process setup ---------------------------------------------------

int qimeBridgeServerStart(void) {
    @autoreleasepool {
        // Referenced only by name from Info.plist's
        // InputMethodServerControllerClass, so touch the class explicitly
        // rather than trusting the linker to keep an apparently unused one.
        (void)[QuiIMEController class];

        NSBundle *bundle = [NSBundle mainBundle];
        NSString *connection =
            [bundle objectForInfoDictionaryKey:@"InputMethodConnectionName"];
        NSString *bundleID = [bundle bundleIdentifier];
        if (connection.length == 0 || bundleID.length == 0) {
            NSLog(@"q-ime: Info.plist missing InputMethodConnectionName or "
                  @"CFBundleIdentifier");
            return 0;
        }
        gServer = [[IMKServer alloc] initWithName:connection
                                bundleIdentifier:bundleID];
        if (gServer == nil) {
            NSLog(@"q-ime: IMKServer init failed for connection %@", connection);
            return 0;
        }
        // Plain %@ here: NSLog is not os_log, so %{public}@ is not a thing
        // it understands. This one line being redacted in the unified log is
        // fine — the Go half logs the same fact, unredacted, to its file.
        NSLog(@"q-ime: server up (connection=%@)", connection);
        return 1;
    }
}

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#import <Carbon/Carbon.h>

int qimeBridgeRegisterSelf(void) {
    @autoreleasepool {
        NSURL *url = [[NSBundle mainBundle] bundleURL];
        OSStatus status = TISRegisterInputSource((__bridge CFURLRef)url);
        if (status != noErr) {
            fprintf(stderr, "q-ime: TISRegisterInputSource failed: %d\n",
                    (int)status);
            return 0;
        }
        fprintf(stdout, "q-ime: registered %s\n", url.fileSystemRepresentation);
        return 1;
    }
}
#pragma clang diagnostic pop

// --- client lifetime -------------------------------------------------

void *qimeBridgeRetainClient(void *client) {
    if (client == NULL) return NULL;
    // CFBridgingRetain, not __bridge_retained, so the ownership transfer is
    // spelled out at the call site rather than hidden in a cast.
    return (void *)CFBridgingRetain((__bridge id)client);
}

void qimeBridgeReleaseClient(void *client) {
    if (client == NULL) return;
    CFBridgingRelease(client);
}

// --- talking back to the host app ------------------------------------

static id<IMKTextInput> quiClient(void *client) {
    return (__bridge id<IMKTextInput>)client;
}

// The marked text is sent as an ATTRIBUTED string built by IMK's own helper,
// not as a bare NSString and not with attributes assembled here.
//
// IMKInputSession.h says a plain NSString "will produce default marking".
// Default marking draws an underline and carries no NSMarkedClauseSegment
// attribute — which is how a client learns that the marked run is one editable
// unit. Cocoa text views cope; a client that maintains its own composition
// model does not. Java/Swing maps clause segments onto AWT
// InputMethodHighlight runs and derives the caret from them.
//
// The two frameworks disagree about what NSMarkedClauseSegment means: AppKit
// documents it as a clause index, while markForStyle:atRange: stores THE STYLE
// ITSELF under it, and TSM styles start at 1. Calling Apple's helper sidesteps
// the disagreement — whatever it writes is by definition what IMK's clients
// read. It is also what Squirrel, the Rime frontend, does.
//
// kTSMHiliteSelectedRawText, not kTSMHiliteConvertedText: the preedit is
// romanised input the user is still editing, not text this input method has
// converted. A pinyin composition is one such run — the syllable boundaries
// are already visible as apostrophes in the text — so there is a single clause
// and no reason to invent more for a client to disagree about.
static NSAttributedString *quiMarkedText(NSString *text) {
    NSRange whole = NSMakeRange(0, text.length);
    IMKInputController *controller = gController;
    if (controller != nil) {
        NSDictionary *attrs = [controller markForStyle:kTSMHiliteSelectedRawText
                                              atRange:whole];
        if (attrs != nil) {
            return [[NSAttributedString alloc] initWithString:text attributes:attrs];
        }
    }
    // No controller has handled an event yet, which should not happen —
    // marked text only exists because a key arrived. Fall back to the style
    // value IMK would have written rather than to a bare string.
    return [[NSAttributedString alloc]
        initWithString:text
            attributes:@{
                NSUnderlineStyleAttributeName : @(NSUnderlineStyleThick),
                NSMarkedClauseSegmentAttributeName : @(kTSMHiliteSelectedRawText),
            }];
}

// quiReportCaret logs when a client puts the insertion point somewhere other
// than where the marked text asked for it.
//
// This exists because that disagreement is invisible from this side unless we
// ask. It is silent in a client that behaves, so it costs a log line only
// where there is something to say.
static void quiReportCaret(id<IMKTextInput> c, NSUInteger want) {
    static int reported = 0;
    if (reported >= 8) return; // one composition's worth, not a per-keystroke flood

    NSRange marked = [c markedRange];
    NSRange sel = [c selectedRange];
    if (marked.location == NSNotFound) return; // client is not tracking a composition
    NSUInteger expect = marked.location + want;
    if (sel.location == expect) return;        // honoured; nothing to report

    reported++;
    char buf[256];
    snprintf(buf, sizeof buf,
             "client %s put the caret at %ld (len %ld); asked for %lu "
             "[marked %ld+%ld, doc len %ld]",
             [[c bundleIdentifier] UTF8String] ?: "?",
             (long)sel.location, (long)sel.length, (unsigned long)expect,
             (long)marked.location, (long)marked.length, (long)[c length]);
    qimeBridgeGoLog(buf);
}

void qimeBridgeSetMarkedText(void *client, const char *utf8) {
    @autoreleasepool {
        id<IMKTextInput> c = quiClient(client);
        if (c == nil) return;
        NSString *text = [NSString stringWithUTF8String:utf8 ? utf8 : ""];

        // selectionRange is relative to the STRING, not to the document, and
        // (length, 0) is the documented spelling of "caret after the last
        // character" — IMKInputSession.h uses exactly this example. Verified
        // against the header rather than changed: it was already right.
        [c setMarkedText:quiMarkedText(text)
          selectionRange:NSMakeRange(text.length, 0)
        replacementRange:NSMakeRange(NSNotFound, NSNotFound)];

        if (text.length > 0) {
            quiReportCaret(c, text.length);
        }
    }
}

void qimeBridgeInsertText(void *client, const char *utf8) {
    @autoreleasepool {
        id<IMKTextInput> c = quiClient(client);
        if (c == nil || utf8 == NULL || utf8[0] == '\0') return;
        [c insertText:[NSString stringWithUTF8String:utf8]
    replacementRange:NSMakeRange(NSNotFound, NSNotFound)];
    }
}

int qimeBridgeCaretRect(void *client, int *x, int *y, int *w, int *h) {
    @autoreleasepool {
        id<IMKTextInput> c = quiClient(client);
        if (c == nil) return 0;
        NSRect caret = NSZeroRect;
        // The returned rect is in Cocoa screen coordinates: bottom-left
        // origin, y growing upward.
        [c attributesForCharacterIndex:0 lineHeightRectangle:&caret];
        if (NSIsEmptyRect(caret)) return 0;

        // Convert to the top-left origin every coordinate crossing qui's
        // platform seam uses. The reference height is the PRIMARY screen's,
        // matching what the cocoa backend's setPos flips against — using
        // the caret's own screen would put a panel on a secondary display
        // at the wrong height.
        NSArray<NSScreen *> *screens = [NSScreen screens];
        CGFloat primaryHeight =
            screens.count > 0 ? NSMaxY([screens[0] frame]) : 0;

        if (x) *x = (int)lround(caret.origin.x);
        // Top edge of the caret in top-left space.
        if (y) *y = (int)lround(primaryHeight - NSMaxY(caret));
        if (w) *w = (int)lround(caret.size.width);
        if (h) *h = (int)lround(caret.size.height);
        return 1;
    }
}
