// Command emojic compiles rime-ice's emoji map into the flat table
// internal/emoji embeds.
//
//	go run ./apps/q-ime/tools/emojic \
//	    -src /opt/test/rime-ice/others/emoji-map.txt \
//	    -o apps/q-ime/internal/emoji/data/emoji.txt
//
// # Why this source
//
// `others/emoji-map.txt` is the hand-written map, not the generated
// `opencc/emoji.txt`. Both ship in rime-ice and they hold the same pairs, but
// the map is the one a person edits and its header says what was left out:
// glyphs that render badly (❤ ☹), emoji too similar to describe apart, and the
// gender-neutral people (中性服务员💁) where only the gendered forms survive.
// That curation is the valuable part, exactly as it is for the English list —
// and it is the same upstream, at the same version, under the same licence, so
// this adds no second data source.
//
// # Shape
//
// The source is emoji-first, one line per emoji:
//
//	😄 开心 高兴 笑
//
// The output is inverted to WORD-first and sorted, because that is the
// direction the input method reads it:
//
//	开心	😄
//	笑	😄	😊
//
// Inverting here rather than at runtime keeps the runtime a binary search over
// an embedded blob with no map to build at startup — see package emoji.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	var (
		src = flag.String("src", "/opt/test/rime-ice/others/emoji-map.txt",
			"rime-ice emoji map")
		out = flag.String("o", "apps/q-ime/internal/emoji/data/emoji.txt",
			"where to write the compiled table")
	)
	flag.Parse()

	f, err := os.Open(*src)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer f.Close()

	// Insertion order is preserved per word: the map lists an emoji's keywords
	// in a deliberate order and the file is ordered by Unicode release, so the
	// first emoji offered for 笑 is the one the author put first. There is no
	// frequency data to do better with, and alphabetical order of glyphs would
	// be meaningless.
	words := map[string][]string{}
	seen := map[string]bool{}
	var order []string
	emojiCount := 0

	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		emoji, keys := fields[0], fields[1:]
		emojiCount++
		for _, k := range keys {
			if k == "" {
				continue
			}
			pair := k + "\x00" + emoji
			if seen[pair] {
				continue // the same emoji listed twice under one word
			}
			seen[pair] = true
			if _, ok := words[k]; !ok {
				order = append(order, k)
			}
			words[k] = append(words[k], emoji)
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	sort.Strings(order) // the runtime binary-searches this

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	w, err := os.Create(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	defer w.Close()
	bw := bufio.NewWriter(w)
	fmt.Fprintf(bw, "# generated by tools/emojic from %s — do not edit\n", filepath.Base(*src))
	fmt.Fprintf(bw, "# %d words, %d emoji; source: rime-ice (GPL-3.0), data from unicode.org emoji charts\n",
		len(order), emojiCount)
	for _, k := range order {
		fmt.Fprintf(bw, "%s\t%s\n", k, strings.Join(words[k], "\t"))
	}
	if err := bw.Flush(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s: %d words, %d emoji\n", *out, len(order), emojiCount)
}
